// Biome catalogue and environmental properties

import { BiomeType } from '../core/Types';

export interface BiomeConfig {
  type: BiomeType;
  name: string;
  description: string;
  icon: string;
  baseColor: string;
  accentColor: string;
  elevationMin: number;
  elevationMax: number;
  tempMin: number;
  tempMax: number;
  moistureMin: number;
  moistureMax: number;
  walkable: boolean;
  walkSpeedMod: number;
  decorations: string[];
}

export const BIOME_CONFIGS: Record<BiomeType, BiomeConfig> = {
  [BiomeType.DEEP_OCEAN]: {
    type: BiomeType.DEEP_OCEAN,
    name: 'Deep Ocean',
    description: 'Vast abyss of azure water. Unfathomable depths.',
    icon: '🌊',
    baseColor: '#1a365d',
    accentColor: '#0f2942',
    elevationMin: -1.0,
    elevationMax: -0.4,
    tempMin: 5,
    tempMax: 20,
    moistureMin: 80,
    moistureMax: 100,
    walkable: false,
    walkSpeedMod: 0.1,
    decorations: ['waves', 'foam'],
  },
  [BiomeType.COASTAL_WATER]: {
    type: BiomeType.COASTAL_WATER,
    name: 'Coastal Waters',
    description: 'Shallow turquoise sea along the shoreline.',
    icon: '💧',
    baseColor: '#2b6cb0',
    accentColor: '#3182ce',
    elevationMin: -0.4,
    elevationMax: -0.05,
    tempMin: 12,
    tempMax: 26,
    moistureMin: 70,
    moistureMax: 100,
    walkable: false,
    walkSpeedMod: 0.3,
    decorations: ['ripples', 'fish_shadow'],
  },
  [BiomeType.SAND_BEACH]: {
    type: BiomeType.SAND_BEACH,
    name: 'Sandy Coast',
    description: 'Sun-warmed golden sand dunes along water edges.',
    icon: '🏖️',
    baseColor: '#ecc94b',
    accentColor: '#d69e2e',
    elevationMin: -0.05,
    elevationMax: 0.08,
    tempMin: 18,
    tempMax: 35,
    moistureMin: 20,
    moistureMax: 60,
    walkable: true,
    walkSpeedMod: 0.9,
    decorations: ['seashell', 'driftwood', 'pebbles'],
  },
  [BiomeType.LUSH_MEADOW]: {
    type: BiomeType.LUSH_MEADOW,
    name: 'Lush Meadow',
    description: 'Emerald plains teeming with wild flowers and gentle breezes.',
    icon: '🌱',
    baseColor: '#48bb78',
    accentColor: '#38a169',
    elevationMin: 0.05,
    elevationMax: 0.35,
    tempMin: 15,
    tempMax: 28,
    moistureMin: 45,
    moistureMax: 80,
    walkable: true,
    walkSpeedMod: 1.0,
    decorations: ['flower_red', 'flower_yellow', 'flower_blue', 'grass_tuft'],
  },
  [BiomeType.DENSE_FOREST]: {
    type: BiomeType.DENSE_FOREST,
    name: 'Dense Woodland',
    description: 'Canopy of ancient oak, birch, and pine trees.',
    icon: '🌲',
    baseColor: '#276749',
    accentColor: '#1c4532',
    elevationMin: 0.1,
    elevationMax: 0.5,
    tempMin: 10,
    tempMax: 24,
    moistureMin: 55,
    moistureMax: 90,
    walkable: true,
    walkSpeedMod: 0.85,
    decorations: ['mushroom', 'fallen_log', 'tree_pine', 'tree_oak'],
  },
  [BiomeType.FARMLAND]: {
    type: BiomeType.FARMLAND,
    name: 'Settler Farmlands',
    description: 'Tilled fertile fields with rows of ripe crops.',
    icon: '🌾',
    baseColor: '#b7791f',
    accentColor: '#975a16',
    elevationMin: 0.08,
    elevationMax: 0.3,
    tempMin: 14,
    tempMax: 30,
    moistureMin: 40,
    moistureMax: 75,
    walkable: true,
    walkSpeedMod: 0.95,
    decorations: ['wheat_stalk', 'furrow', 'scarecrow'],
  },
  [BiomeType.SETTLEMENT]: {
    type: BiomeType.SETTLEMENT,
    name: 'Settlement & Roads',
    description: 'Cobblestone streets, hearth cottages, and gathering halls.',
    icon: '🏡',
    baseColor: '#718096',
    accentColor: '#4a5568',
    elevationMin: 0.08,
    elevationMax: 0.35,
    tempMin: 12,
    tempMax: 28,
    moistureMin: 30,
    moistureMax: 70,
    walkable: true,
    walkSpeedMod: 1.25, // Fast movement on paved roads!
    decorations: ['lantern', 'wooden_fence', 'cobble_stones'],
  },
  [BiomeType.ROCKY_HILLS]: {
    type: BiomeType.ROCKY_HILLS,
    name: 'Rocky Highlands',
    description: 'Rugged ridges rich in iron ore and cut stone.',
    icon: '⛰️',
    baseColor: '#a0aec0',
    accentColor: '#718096',
    elevationMin: 0.35,
    elevationMax: 0.7,
    tempMin: 2,
    tempMax: 18,
    moistureMin: 15,
    moistureMax: 50,
    walkable: true,
    walkSpeedMod: 0.75,
    decorations: ['boulder', 'ore_vein', 'gravel'],
  },
  [BiomeType.SNOW_PEAK]: {
    type: BiomeType.SNOW_PEAK,
    name: 'Snowy Summit',
    description: 'Glacial mountain tops enveloped in perennial frost.',
    icon: '❄️',
    baseColor: '#edf2f7',
    accentColor: '#cbd5e0',
    elevationMin: 0.7,
    elevationMax: 1.0,
    tempMin: -15,
    tempMax: 0,
    moistureMin: 30,
    moistureMax: 80,
    walkable: true,
    walkSpeedMod: 0.65,
    decorations: ['snow_drift', 'ice_shard', 'pine_snow'],
  },
  [BiomeType.MYSTIC_GROVE]: {
    type: BiomeType.MYSTIC_GROVE,
    name: 'Mystic Mana Grove',
    description: 'Sanctuary of glowing azure flora and resonating ley-lines.',
    icon: '🔮',
    baseColor: '#805ad5',
    accentColor: '#553c9a',
    elevationMin: 0.15,
    elevationMax: 0.55,
    tempMin: 12,
    tempMax: 22,
    moistureMin: 60,
    moistureMax: 95,
    walkable: true,
    walkSpeedMod: 1.1,
    decorations: ['mana_crystal', 'runestone', 'glowing_spores', 'wisp_nest'],
  },
  [BiomeType.VOLCANIC_CRATER]: {
    type: BiomeType.VOLCANIC_CRATER,
    name: 'Volcanic Fissure',
    description: 'Obsidian crags with veins of bubbling molten magma.',
    icon: '🌋',
    baseColor: '#c53030',
    accentColor: '#742a2a',
    elevationMin: 0.3,
    elevationMax: 0.8,
    tempMin: 35,
    tempMax: 50,
    moistureMin: 0,
    moistureMax: 20,
    walkable: true,
    walkSpeedMod: 0.7,
    decorations: ['magma_crack', 'sulfur_vent', 'obsidian_spire'],
  },
  [BiomeType.DESERT_DUNES]: {
    type: BiomeType.DESERT_DUNES,
    name: 'Desert Dunes',
    description: 'Vast arid sands shaped by endless howling winds.',
    icon: '🏜️',
    baseColor: '#dd6b20',
    accentColor: '#c05621',
    elevationMin: 0.05,
    elevationMax: 0.4,
    tempMin: 28,
    tempMax: 46,
    moistureMin: 0,
    moistureMax: 25,
    walkable: true,
    walkSpeedMod: 0.8,
    decorations: ['cactus', 'sand_ripple', 'bones'],
  },
};
